# pnpm-workspace.yaml
packages:
  # Examples: The apps for the examples
  - 'examples/hello-world/*'
  - 'examples/lolalemon/*'
  - 'examples/pokedex/*'
  - 'examples/tweeter/*'

  # Packages:
  - 'packages/*'
